### ISSUE TITLE
Build Instructions

### ISSUE THREAD

**Issue by amtrivedi91** [osu-cass/whats-fresh-mobile#67]
I was interested in contributing to the project but am unsure of where to start as I could not find any build instructions. Can you please provide the same so that me (and others who are interested) could begin contributing?

**Comment by jhcarr** [comment]
At the moment, the README is the only comprehensive developer documentation on this project and prior to #70 it was badly out-of-date because it still referred to the prototype project that this one came from.

Hopefully this update to the README will help you get started while we update our */docs* to include a more complete set of developer docs.

Also: feel free to reach out to me or any of the project contributors directly on IRC.
